--------------------------------------------------------
--  File created - סנוהא-ÿםגאנÿ-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "ROOT"."BOOK" 
   (	"BOOK_ID" NUMBER, 
	"TITLE" VARCHAR2(100 CHAR), 
	"AUTHOR" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK_ITEMS
--------------------------------------------------------

  CREATE TABLE "ROOT"."BOOK_ITEMS" 
   (	"ITEM_ID" NUMBER, 
	"BOOK_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table READERS
--------------------------------------------------------

  CREATE TABLE "ROOT"."READERS" 
   (	"READER_ID" NUMBER, 
	"NAME" VARCHAR2(50 CHAR), 
	"PASSWORD" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAKEN_BOOKS
--------------------------------------------------------

  CREATE TABLE "ROOT"."TAKEN_BOOKS" 
   (	"ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"READER_ID" NUMBER, 
	"DATE_RETURN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence BOOK_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."BOOK_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence READERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."READERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAKEN_BOOKS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."TAKEN_BOOKS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ROOT.BOOK
SET DEFINE OFF;
Insert into ROOT.BOOK (BOOK_ID,TITLE,AUTHOR) values ('1','title1','author1');
REM INSERTING into ROOT.BOOK_ITEMS
SET DEFINE OFF;
Insert into ROOT.BOOK_ITEMS (ITEM_ID,BOOK_ID) values ('1','1');
REM INSERTING into ROOT.READERS
SET DEFINE OFF;
Insert into ROOT.READERS (READER_ID,NAME,PASSWORD) values ('1','name1','a722c63db8ec8625af6cf71cb8c2d939');
REM INSERTING into ROOT.TAKEN_BOOKS
SET DEFINE OFF;
Insert into ROOT.TAKEN_BOOKS (ID,ITEM_ID,READER_ID,DATE_RETURN) values ('2','1','1',to_date('31.01.17','DD.MM.RR'));
--------------------------------------------------------
--  DDL for Index BOOK_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."BOOK_ITEMS_PK" ON "ROOT"."BOOK_ITEMS" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."BOOK_PK" ON "ROOT"."BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index READERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."READERS_PK" ON "ROOT"."READERS" ("READER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAKEN_BOOKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."TAKEN_BOOKS_PK" ON "ROOT"."TAKEN_BOOKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger BOOK_ITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."BOOK_ITEMS_TRG" 
BEFORE INSERT ON BOOK_ITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ITEM_ID IS NULL THEN
      SELECT BOOK_ITEMS_SEQ.NEXTVAL INTO :NEW.ITEM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ROOT"."BOOK_ITEMS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."BOOK_TRG" 
BEFORE INSERT ON BOOK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BOOK_ID IS NULL THEN
      SELECT BOOK_SEQ.NEXTVAL INTO :NEW.BOOK_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ROOT"."BOOK_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger READERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."READERS_TRG" 
BEFORE INSERT ON READERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ROOT"."READERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TAKEN_BOOKS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."TAKEN_BOOKS_TRG" 
BEFORE INSERT ON TAKEN_BOOKS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TAKEN_BOOKS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ROOT"."TAKEN_BOOKS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "ROOT"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."BOOK" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK_ITEMS
--------------------------------------------------------

  ALTER TABLE "ROOT"."BOOK_ITEMS" ADD CONSTRAINT "BOOK_ITEMS_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."BOOK_ITEMS" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."BOOK_ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table READERS
--------------------------------------------------------

  ALTER TABLE "ROOT"."READERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."READERS" ADD CONSTRAINT "READERS_PK" PRIMARY KEY ("READER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."READERS" MODIFY ("READER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAKEN_BOOKS
--------------------------------------------------------

  ALTER TABLE "ROOT"."TAKEN_BOOKS" ADD CONSTRAINT "TAKEN_BOOKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."TAKEN_BOOKS" MODIFY ("DATE_RETURN" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TAKEN_BOOKS" MODIFY ("READER_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TAKEN_BOOKS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."TAKEN_BOOKS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOK_ITEMS
--------------------------------------------------------

  ALTER TABLE "ROOT"."BOOK_ITEMS" ADD CONSTRAINT "BOOK_ITEMS_FK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "ROOT"."BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKEN_BOOKS
--------------------------------------------------------

  ALTER TABLE "ROOT"."TAKEN_BOOKS" ADD CONSTRAINT "TAKEN_BOOKS_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "ROOT"."BOOK_ITEMS" ("ITEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."TAKEN_BOOKS" ADD CONSTRAINT "TAKEN_BOOKS_READER" FOREIGN KEY ("READER_ID")
	  REFERENCES "ROOT"."READERS" ("READER_ID") ON DELETE CASCADE ENABLE;
